# Language Tests are Running In
language: php

# PHP versions to test against
php:
  - 5.4
  - 5.5
  - 5.6

# Node version, if you have JS to test.
#node_js:
#  - "0.10"

# Environment Variables to set
env:
  global:
    - APP_ENV=travis
    # Contains a $GITHUB_TOKEN env var for use with composer to avoid API limits.
    - secure: "GskNShxJTSdczbddmPPIzKivDWn/YuaMFgr5UPSumPDirQQdbesRh/tQZNGiIaROXXnDs45wJCWT2ra8XdYBZouISXOoOZARQgz9JqUHAbkgtCbxa4qhp3ZwDymJMFd5eGvM99r9OCoSh2us+E2fhBb1+P5kvS6laB5TKYmwAX0="

# Services to Enable
services:
  - mysql

# Branches to be built or not
branches:
  # Blacklist these branches
  except:
    - gh-pages

# Before Installing Software/Dependencies Needed
before_install:

# Install Software/Dependencies Needed
install:
  - git submodule update --init --recursive
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - composer install --dev --no-interaction
  - ./bin/set-owner
  - ./bin/set-configs "$APP_ENV"
  - ./bin/writedirs

# Before the Test Script Runs
before_script:
  - phpenv rehash
  - mysql -e 'DROP DATABASE IF EXISTS `travis_app`; CREATE DATABASE `travis_app`;'

# Test Script Call
script:
  - ./bin/run-codesniffer y
  - ./bin/run-tests All --stderr

# After a Successful Build
after_success:

# After a Failed Build
after_failure:

# After every Build
after_script:

# Notifications Settings
notifications:
  email: false

# Github Private Key for an account that can read your private repos
#source_key:
